### PR TITLE
[waiting for go-1.7]add s390x

### PR DESCRIPTION
**Pull request by jordimassaguerpla**

### CODE REVIEW

**Comment by flavio** [comment]
LGTM

**Comment by flavio** [comment]
I have a question though... this code is going to end up inside of the current golang-packaging package. However we don't have yet an official go 1.7 package that officially supports s390x. Is this going to cause issues in the meantime?

**Comment by jordimassaguerpla** [comment]
good point.
Then I would say to wait until we have go-1.7.

**Comment by flavio** [comment]
Sounds good to me.

**Comment by marguerite** [comment]
@jordimassaguerpla 

This has been accidentally achieved through one of my previous commits. but of course I'll manual merge and keep your credit.

**Pull request closed without merging**
